#!/bin/bash
GIT_REPO='git@git.ipo.com:'
PS3="select app name: "

select GIT_APP in exit $(cat $HOME/bin/git/app.conf); do
    case $GIT_APP in 
        exit)
            echo 'bye'
            break
            ;;
        *)
            echo "$GIT_REPO/${GIT_APP}.git"
            break
            ;;
    esac
done
